name: License check
description: Checks licenses of node modules
author: code quest sp. z o.o.
inputs:
  allowLicenses:
    description: Allow licenses that use these licenses
    required: false
    default: |
      AFL-3.0
      Apache-2.0
      Artistic-2.0
      BSD-2-Clause
      BSD-3-Clause-Clear
      BSD-3-Clause
      BSD-4-Clause
      BSL-1.0
      CC-BY-4.0
      ECL-2.0
      ISC
      MIT
      MS-PL
      NCSA
      OFL-1.1
      PostgreSQL
      UPL-1.0
      Zlib

  allowUnknown:
    description: Allow modules with unknown licenses
    required: false
    default: "false"

  ignoreModules:
    description: List of ignored modules
    required: false
    default: ""

  ignoreDevelopment:
    description: Ignore development dependencies
    required: false
    default: "false"

runs:
  using: "node14"
  main: "dist/index.js"
